# str=" eswaryarapatni "
# print(len(str))
# print(str.capitalize())
# print(str.title())
# print(str.count("a"))
# print(str.count("a",1,4))
# print(str.endswith("i"))
# print(str.isalpha())
# print(str.isdecimal())
# print(str.isnumeric())
# print(str.isidentifier())
# print(str.replace("eswar","esu"))
# print(str.split())
# print(str.upper())

a=[3,1,8,5,0,8,5]
print(a)
# print(a.clear())
print(a.pop())
a.append(9)
a.remove(5)
a.reverse()
a.sort()
print(a)
print(a.index(3))